spring:
  application:
    name: auth-service
server:
  port: 8081
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: auth
    password: auth123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true