services:
  kafka:
    image: apache/kafka:3.7.2
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME:-authdb}
      POSTGRES_USER: ${AUTH_DB_USERNAME:-auth}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-auth123}
    ports: ["${AUTH_DB_PORT:-5433}:5432"]

  wallet-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${WALLET_DB_NAME:-walletdb}
      POSTGRES_USER: ${WALLET_DB_USERNAME:-wallet}
      POSTGRES_PASSWORD: ${WALLET_DB_PASSWORD:-wallet123}
    ports: ["${WALLET_DB_PORT:-5434}:5432"]

  transfer-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${TRANSFER_DB_NAME:-transferdb}
      POSTGRES_USER: ${TRANSFER_DB_USERNAME:-transfer}
      POSTGRES_PASSWORD: ${TRANSFER_DB_PASSWORD:-transfer123}
    ports: ["${TRANSFER_DB_PORT:-5435}:5432"]

  ledger-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${LEDGER_DB_NAME:-ledgerdb}
      POSTGRES_USER: ${LEDGER_DB_USERNAME:-ledger}
      POSTGRES_PASSWORD: ${LEDGER_DB_PASSWORD:-ledger123}
    ports: ["${LEDGER_DB_PORT:-5436}:5432"]

volumes:
  kafka_data:
