spring:
  application:
    name: wallet-service
  datasource:
    url: ${WALLET_DB_URL}
    username: ${WALLET_DB_USERNAME}
    password: ${WALLET_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${WALLET_SERVICE_PORT}

logger-service:
  base-url: ${LOGGER_SERVICE_BASE_URL}

auth-service:
  base-url: ${AUTH_SERVICE_BASE_URL}

internal:
  api-key: ${INTERNAL_API_KEY}

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET}

wallet:
  kafka:
    topic: ${WALLET_KAFKA_TOPIC}
